# docker-compose file for production purposes

version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    stdin_open: true
    command: >
      sh -c " cd app && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/crypton/web/app/static
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - sess

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env.db.prod

  sess:
    image: redis:alpine
    ports:
      - 6379:6379

  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile.prod
    volumes:
      - static_volume:/home/crypton/web/app/static
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  static_volume: