# docker-compose file for development purposes

version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - "./:/crypton/"
    command: python app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - sess

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=not-bots

  sess:
    image: redis:alpine
    ports:
      - 6379:6379