# Generated by Django 3.0.8 on 2020-07-27 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200727_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
