# Generated by Django 3.0.8 on 2020-07-27 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200727_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='crypto_key',
            field=models.IntegerField(editable=False, help_text='Unique key for internal operations', unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
